version: "3.9"

services:
  web:
    build: .
    image: mental_clinic
    env_file: .env
    command: sh -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/mental_health_coaching

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5000:5000

  sidekiq:
    image: mental_clinic:latest
    command: sidekiq
    volumes:
      - .:/mental_health_coaching
    env_file:
      - .env

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
